---
- hosts: localhost

  gather_facts: no
  vars:
    server_roles:
      - role2

  tasks:
    - include_role: name=dependency-or-standalone
      when: '"dependency-or-standalone" in server_roles|default([])'

    - include_role: name=role1
      when: '"role1" in server_roles|default([])'

    - include_role: name=role2
      when: '"role2" in server_roles|default([])'
